# Generated by Django 3.0.8 on 2020-07-16 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheese',
            old_name='firms',
            new_name='firmness',
        ),
    ]
